### ISSUE TITLE
'CapacitorSQLite-open': Open: No available connection for...

### ISSUE THREAD

**Issue by pkzOR** [capacitor-community/sqlite#163]
On Windows 10;
building an Electron/Vue app

Using:
    "@capacitor-community/electron": "^4.0.3",
    "@capacitor-community/sqlite": "^3.2.0-5",
    "@capacitor/core": "^3.2.0",

Code:
import { CapacitorSQLite, SQLiteConnection } from '@capacitor-community/sqlite';
...
 async createDb(): Promise<void> {
    const capLite = new SQLiteConnection(CapacitorSQLite);
    const db = await capLite.createConnection('inspector', false, 'no-encryption', 1);
    await db.open();
}

**Expected behavior**
The Databases folder gets created under the C:\Users\<my user name>, as expected,  but no database is created. 

What else should I be doing?

**Comment by jepiqueau** [comment]
@pkzOR This has been fixed in release  3.2.0-8 you can now have electron in the name of your app. thanks for your feedback and on how to use Ctrl+P or Command+P on Mac. pretty handy. i learnt something. I will close the issue

**Comment by pkzOR** [comment]
@jepiqueau I am  still not seeing the db being created w/ 3.2.0-8.   My repo was named electron-sqlite, but not the app. So I am confused as to what you saw and how my example now creates a db.

**Comment by jepiqueau** [comment]
@pkzOR to find the application name we read the package.json file and the path was .../electron-sqlite/package.json so now if you look at your users folder you should find a databases folder with a folder YOUR_APPLICATION_NAME as in your package.json and inside that folder your two databases

**Comment by pkzOR** [comment]
@jepiqueau  My repo is named electron-sqlite, but my code lives in a different folder name. C:\Users\myusername\databases\pkzinspector gets created, but there ar no dbs in there.  As in the screenshot above, what I see on line 84 of UseSqlite  is that  r is undefined, but hovering over it shows there is a dbname.

I am sorry for the confusion here and appreciate your efforts, but I am still lost.  Does my code create the dbs when you run it?

**Comment by jepiqueau** [comment]
@pkzOR i made a PR in `https://github.com/pkzOR/electron-sqlite`normally it works

**Comment by jepiqueau** [comment]
@pkzOR i also test it under Windows 10 and it works

**Comment by pkzOR** [comment]
Thanks again.
